//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 863232937972244.
        /// </summary>
        internal static string Cloudinary_API_Key {
            get {
                return ResourceManager.GetString("Cloudinary_API_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esk9SYhXjvx_uTDwNue61AAGT3c.
        /// </summary>
        internal static string Cloudinary_API_Secret {
            get {
                return ResourceManager.GetString("Cloudinary_API_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dzaoyffio.
        /// </summary>
        internal static string Cloudinary_Cloud_Name {
            get {
                return ResourceManager.GetString("Cloudinary_Cloud_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyCfDHPbyqGPwBRCsUCQE0nxUzDHCNndbn8.
        /// </summary>
        internal static string Google_API_Key {
            get {
                return ResourceManager.GetString("Google_API_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=sql12.freesqldatabase.com;Database=sql12739505;User Id=sql12739505;Password=bI2s32U2vF;Port=3306;Charset=utf8mb4;.
        /// </summary>
        internal static string MySqlConnection {
            get {
                return ResourceManager.GetString("MySqlConnection", resourceCulture);
            }
        }
    }
}
